volumes:
  snowflake:

services:
  snowflake:
    container_name: snowflake
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        # Default to debug, can be overridden via environment variable
        BUILD_MODE: ${BUILD_MODE:-debug}
    image: snowflake:latest
    entrypoint: /bin/true
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  bootstrap:
    container_name: bootstrap
    image: snowflake:latest
    volumes:
      - snowflake:/shared
    entrypoint:
      - /bin/bash
      - ./docker/bootstrap.sh
    depends_on:
      - snowflake

  peer1:
    container_name: peer1
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: snowflake:latest
    hostname: peer1
    ports:
      - "3001:3001"
      - "4001:4001"
    network_mode: host
    volumes:
      - snowflake:/shared
    depends_on:
      - bootstrap

  peer2:
    container_name: peer2
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: snowflake:latest
    hostname: peer2
    ports:
      - "3002:3002"
      - "4002:4002"
    network_mode: host
    volumes:
      - snowflake:/shared
    depends_on:
      - bootstrap

  peer3:
    container_name: peer3
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: snowflake:latest
    hostname: peer3
    ports:
      - "3003:3003"
      - "4003:4003"
    network_mode: host
    volumes:
      - snowflake:/shared
    depends_on:
      - bootstrap
