version: '3.8'

services:
  bootstrap:
    image: rust-peer:latest
    volumes:
      - shared:/shared
    command: bash bootstrap.sh

  peer1:
    image: rust-peer:latest
    hostname: peer1
    volumes:
      - shared:/shared
    depends_on:
      - bootstrap

  peer2:
    image: rust-peer:latest
    hostname: peer2
    volumes:
      - shared:/shared
    depends_on:
      - bootstrap

  peer3:
    image: rust-peer:latest
    hostname: peer3
    volumes:
      - shared:/shared
    depends_on:
      - bootstrap

volumes:
  shared:
