volumes:
  snowflake:

services:
  snowflake:
    container_name: snowflake
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        # Default to debug, can be overridden via environment variable
        BUILD_MODE: ${BUILD_MODE:-debug}
    image: snowflake:latest
    network_mode: host
    healthcheck:
      test: [ "CMD", "/app/docker/check_anr_ready.sh" ]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 40s
    entrypoint:
      - /bin/bash
      - ./docker/setup.sh
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  bootstrap:
    container_name: bootstrap
    image: snowflake:latest
    network_mode: host
    volumes:
      - snowflake:/shared
    entrypoint:
      - /bin/bash
      - ./docker/bootstrap.sh
    depends_on:
      snowflake:
        condition: service_healthy

  peer1:
    container_name: peer1
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: snowflake:latest
    hostname: peer1
    network_mode: host
    volumes:
      - snowflake:/shared
    depends_on:
      - bootstrap
    environment:
      - PEER_ARGS=--sync-headers

  peer2:
    container_name: peer2
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: snowflake:latest
    hostname: peer2
    network_mode: host
    volumes:
      - snowflake:/shared
    depends_on:
      - bootstrap

  peer3:
    container_name: peer3
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: snowflake:latest
    hostname: peer3
    network_mode: host
    volumes:
      - snowflake:/shared
    depends_on:
      - bootstrap
