# .github/workflows/workflow.yml
name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install protoc
        run: sudo apt install -y protobuf-compiler

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Check proto
        run: make proto-check

      - name: Run Clippy
        run: make clippy

      - name: Check formatting
        run: make fmt-check

      - name: Run Tests
        run: make test